name: Qodana

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  qodana-scan:
    name: Qodana Scan
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.2
        with:
          upload-result: ${{ startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/develop') }}
          args: --baseline qodana.sarif.json --ide QDNET
          pr-mode: ${{ github.event_name == 'pull_request' }}
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}


